### ISSUE TITLE
Question: can I route queries based on *existing* labels

### ISSUE THREAD

**Issue by raffraffraff** [jacksontj/promxy#125]
When you add labels to the [`labels` section ](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L31), this does two things:
1. _Add_ a label to the metrics
2. Restrict queries to the group that has that label

We've got multiple datacenters, and each one already has its own datacenter label, so I don't want to add another. For one thing, they would not apply to historical metrics. But for another, I don't want to have to update a bunch of dashboards with a new label in the queries.

Question: can I get Promxy to filter on an _existing_ label without trying to add it? (We have tried, and it didn't work)

**Comment by jacksontj** [comment]
>  can I get Promxy to filter on an _existing_ label without trying to add it?

It depends on what you mean by this. The short answer is no-- promxy will always add it if configured in `labels`-- but if the label is already always present on prometheus then its effectively a no-op. Lets take an example query of `foo{region="us-west"}` and the following promxy config:

```yaml
promxy:
  server_groups:
    - static_configs:
        - targets:
          - localhost:9090
      labels:
        sg: localhost_9090
    - static_configs:
        - targets:
          - localhost:9091
```

In this example the query would be sent to *both* server groups, but the result would only contain data that matches (the fitlers are still honored on the remote prometheus). As you pointed out the `labels` section both adds a label and restricts query routing, so if I were to change the query to be `foo{region="us-west", sg="localhost_9090"}` then it would only be sent to a single servergroup. The reason why is that [during query processing](https://github.com/jacksontj/promxy/blob/master/servergroup/servergroup.go#L294) we filter out queries that we know won't match the servergroup based on our local configuration (in this case the labels we have in the config).

That all being said, if you had your remote prometheus hosts configured to always add a label `region="us-west"` (for example) then you can still add that `labels` configuration to promxy as it would "overwrite" the label -- but since its a match, you get the same result. This would allow promxy to filter the query to just the servergroups that would match.

> We've got multiple datacenters, and each one already has its own datacenter label

so if each datacenter already has the label, you should be able to add that label to promxy without issue -- as it will effectively be a no-op.

>  For one thing, they would not apply to historical metrics

to clarify this a bit, this label added by promxy doesn't change how its stored on prom itself (it doens't rewrite the timeseries) it just changes how it is queryable. meaning the label is added at read-time through promxy.

> But for another, I don't want to have to update a bunch of dashboards with a new label in the queries.

In general having more labels return shouldn't be an issue unless you have specific templating or join queries. And added the label doesn't mean you have to query by it, in promql you don't have to filter by all of the labels in the timeseries (technically you only need to do 1, and even that can be a regex).


Hopefully that clarifies some? If not

**Comment by jacksontj** [comment]
@raffraffraff wanted to check in that this helped? If not I'd like to better understand the issue; what you are asking for definitely sounds like something promxy should do :)

**Comment by jacksontj** [comment]
@raffraffraff I'm going to go ahead and close this out-- if this is still unclear or you have any other questions feel free to re-open
