### ISSUE TITLE
add support subquery

### ISSUE THREAD

**Issue by Wing924** [jacksontj/promxy#140]
Since v2.8, prometheus supports subquery. I would be nice if promxy also support it.

**Comment by jacksontj** [comment]
From a quick read, this looks like I'll only need to upgrade the prometheus fork promxy is using. Shouldn't be *tons* of work, but unfortunately non-trivial. I've had upgrading on the list, since some perf improvements have made it into promql specifically (I was waiting for some of the bugs there to settle out, and they seem to have done so).

**Comment by jacksontj** [comment]
@Wing924 if you'd like to try it out #141 is the WIP PR for it. At this point it should be functional (there is also a contianer on quay with tag `prom_2.9`).

**Comment by Wing924** [comment]
@jacksontj 
Thank you! It looks working now.

**Comment by jacksontj** [comment]
Glad to hear! I'll likely merge this in a week or two. Within the first week of 2.9 being out there were 2 bugfixes (already on 2.9.2), so I'll give upstream a bit more time to settle out their bugs etc :)

**Comment by jacksontj** [comment]
Current outlook is 2.10 ; there's still an issue on 2.9.2 (https://github.com/prometheus/prometheus/issues/5524) -- so currently planning on 2.10 once its out and stable.

**Comment by jacksontj** [comment]
#141 merged, this is complete!
