### ISSUE TITLE
Do not fetch raw data from upstream nodes in general case

### ISSUE THREAD

**Issue by valyala** [jacksontj/promxy#176]
### The issue

It looks like Promxy fetches all the raw data points for the given time range in the query from upstream nodes and then merges them. This may take big amounts of network bandwidth, CPU and RAM on both upstream nodes and promxy when the query touches big number of raw data points.

### The solution

Send the original PromQL query to all the upstream nodes and compare results. If they are similar, then just return a single result. Otherwise fall back to the current approach with fetching raw data points and merging them on Promxy side.

**Comment by jacksontj** [comment]
Welcome to the promxy project :)

This is actually one of the core pieces of promxy-- to aggregate data as cheaply as possible. Promxy actually very rarely queries *all* data from the downstreams (only in cases where it *has* to and a couple aggregation methods that just haven't been implemented yet). The "secret sauce", as it were, is the [`NodeReplacer` stuff](https://github.com/jacksontj/promxy/blob/master/pkg/proxystorage/proxy.go#L171). I'll illustrate with a few example queries.

# examples
For these examples we'll assume there are 2 nodes with distinct data (that way we don't have to conflate this example with data merging).

(1) simple aggregation
Lets say the query sent to promxy is `sum(foo)`, in this case I don't need to fetch the raw data from the downstreams as I am myself being asked an aggregation. More specifically this is an aggregation that is "re-entrant" (meaning I can do a sum of sums and its the same as doing a sum on the original set). So in this case you'll actually see that promxy sends the same `sum(foo)` to both downstreams, here is an example from debug logging:

```
DEBU[2019-06-19T08:14:07-07:00] AggregateExpr sum(foo)                       
DEBU[2019-06-19T08:14:07-07:00] http://localhost:9091                         api=Query query="sum(foo)" ts="2019-06-19 08:14:07.806 -0700 PDT"
DEBU[2019-06-19T08:14:07-07:00] http://localhost:9090/example/prefix/api/v1/read  api=Query query="sum(foo)" ts="2019-06-19 08:14:07.806 -0700 PDT"
[::1] - - [19/Jun/2019 15:14:07] "GET /api/v1/query HTTP/1.1 422 150" 0.003076 query=sum%28foo%29&time=1560957247.806&_=1560956867359
```

(2) more complex aggregation
If the query is now something like `sum(sum(sum(foo))` the inner-most aggregation is sent to the downstreams and then the outer aggregations are done on the promxy side. This is important as some of these may have label manipulations that need to aggregate across downstreams, and some aggregations aren't re-entrant. But in this case we still do not query *all* data.

```
DEBU[2019-06-19T08:16:39-07:00] AggregateExpr sum(foo)                       
DEBU[2019-06-19T08:16:39-07:00] http://localhost:9091                         api=Query query="sum(foo)" ts="2019-06-19 08:16:39.126 -0700 PDT"
DEBU[2019-06-19T08:16:39-07:00] http://localhost:9090/example/prefix/api/v1/read  api=Query query="sum(foo)" ts="2019-06-19 08:16:39.126 -0700 PDT"
[::1] - - [19/Jun/2019 15:16:39] "GET /api/v1/query HTTP/1.1 422 150" 0.001929 query=sum%28sum%28sum%28foo%29%29%29&time=1560957399.126&_=1560956867360
```

(3) raw data queries
If the query is something like `foo[1d]` unfortunately there isn't anything promxy can do to reduce the data we'll request from the downstream -- so in this case we will request all of the data (as that was what the query was).

```
DEBU[2019-06-19T08:17:02-07:00] http://localhost:9091                         api=GetValue end="2019-06-19 08:17:02.801 -0700 PDT" matchers="[__name__=\"foo\"]" start="2019-06-18 08:17:02.801 -0700 PDT"
DEBU[2019-06-19T08:17:02-07:00] http://localhost:9090/example/prefix/api/v1/read  api=GetValue end="2019-06-19 08:17:02.801 -0700 PDT" matchers="[__name__=\"foo\"]" start="2019-06-18 08:17:02.801 -0700 PDT"
DEBU[2019-06-19T08:17:02-07:00] Select                                        matchers="[__name__=\"foo\"]" selectParams="&{1560871022801 1560957422801 0 }" took=1.262534ms
```

# conclusion
With the `NodeReplacer` mechanism in place promxy can significantly reduce the raw data it must fetch from downstreams. Because of this we're able to have the [performance we do](https://github.com/jacksontj/promxy#what-is-query-performance-like-with-promxy).


Hopefully that clarifies the behavior a bit. With that context out of the way, if you have a query you are *seeing* raw data fetches please let me know -- barring crazy queries (like 3) it should be very uncommon.

**Comment by valyala** [comment]
> For these examples we'll assume there are 2 nodes with distinct data (that way we don't have to conflate this example with data merging).

I'm sorry for the confusion. I meant upstream replicas with identical data, not shards with distinct data. Upstream replicas usually contain almost identical data with possible small jitter on timestamps and values, since they usually receive data from Prometheus HA pairs. This means that we can send the original PromQL query to all the replicas, compare results and return the result from the first replica if these results are almost identical.

Sometimes the data on replicas may be different. For instance, replica may contain gaps during Prometheus instance maintenance. In this case the returned results from replicas will differ, so we need to resort to fetching raw data from replicas and merging / deduplicating it on Promxy side.

Hope this is more clear now.

**Comment by jacksontj** [comment]
> This means that we can send the original PromQL query to all the replicas, compare results and return the result from the first replica if these results are almost identical.

This is only true if (1) there is only a single "shard" of data or (2) the query is either raw or only re-entrant aggregation.

The aggregation mechanism I described above does basically what you are describing (some details are different, but the idea is the same). Promxy aims to only pull the data required to answer the query.

So, as it stands today doing a full-query of data should be *very* rare (stddev, stdvar, and matrix selectors are the only ones IIRC). So if you are seeing this behavior would you mind sharing the query you are running (ideally with debug logs and the config file)?

**Comment by valyala** [comment]
> This is only true if (1) there is only a single "shard" of data

This is common case for [HA setup in VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/Single-server-VictoriaMetrics#high-availability) - there is only a single "shard" with multiple replicas. This remains true for both single-node and cluster versions.

> So if you are seeing this behavior would you mind sharing the query you are running (ideally with debug logs and the config file)?

There are reports about slower performance with Promxy in front of VictoriaMetrics comparing to querying VictoriaMetrics directly. I'll ask for specific queries and post them here.

**Comment by jacksontj** [comment]
> There are reports about slower performance with Promxy in front of VictoriaMetrics comparing to querying VictoriaMetrics directly. I'll ask for specific queries and post them here.

Thanks, as discussed above the performance should be roughly the same -- so definitely open issues if that is not the case :)

If its alright with you I think I'll close out this issue since its a nice overview of how the data flow works, then we can create new issues (with bug labels) for the performance issues we see.

**Comment by valyala** [comment]
Sounds good!
