### ISSUE TITLE
Weird result when some prometheus goes down in a server group

### ISSUE THREAD

**Issue by soumyaprakashdatta** [jacksontj/promxy#218]
I am pretty new to prometheus - promxy ecosystem. I was testing out the following setup and encountered a weird behavior on metric read from promxy. Please let me know if I am missing something,

Setup details
------------------

Two prometheus process was running, let's call them P1 ( running at port 10001) and P2 (running at port 10002) . Promxy was setup with P1 and P2 in a server group. Now to test some failure mode, I brought down P2 and following was the result. I brought back P2 after a while about 7 mins later.

Observations
------------------

I brought down P2 at around 19:00 and again started it at around 19:07. So expected behavior was data gap during that time period, which is happening for row-1 panels ( data source - P1 and P2 respectively )
But in case of promxy( also the same observation was there for m3db) , it did not show the drop untile 5m passed by. Is this something related to prometheus stale metric treatment? How to work around this, as we should observe an immediate drop around 19:00 .

Image :

<img width="2136" alt="Screenshot 2019-09-11 at 7 29 34 PM" src="https://user-images.githubusercontent.com/5086979/64716188-75132680-d4b1-11e9-8581-ad24f5fa320a.png">

**Comment by jacksontj** [comment]
The 5m delay is a prometheus-ism and it is referred to as a [`lookback delta`](https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go#L240). TLDR; prometheus will use "old" data (up to that delta) in a query response unless a `StaleNan` is sent (more details here -- https://www.robustperception.io/staleness-and-promql). Since you mentioned you are using m3db I'm not sure if it supports the staleness nans -- or the prometheus remote read API. If it supports the remote_read api you can [enable it in promxy](https://github.com/jacksontj/promxy/blob/master/pkg/servergroup/config.go#L29) to pull the StaleNans. Alternatively you can set the same [cli flag](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/main.go#L74) in promxy to achieve the same result.

**Comment by jacksontj** [comment]
It seems that this question is answered, if not please let me know -- for now I'll close this out :)
