### ISSUE TITLE
Entire servergroup being down breaks promxy graph page

### ISSUE THREAD

**Issue by glightfoot** [jacksontj/promxy#230]
During an upgrade, we noticed that if an entire servergroup goes offline, we get the following error when opening the graph page on promxy: `Error loading available metrics!`

**Comment by jacksontj** [comment]
This is actually intended default behavior. If all nodes in a servergroup are down the resulting data can be inaccurate (missing data, etc.) -- so we'd rather by default return an error rather than an inaccurate value (since alerting etc. might rely on it, we don't want to hide the problem).

Now with that said if you'd like to make some or all servergroups "optional" (meaning the errors will be ignored and we'll serve the response anyways) you can do this using the [ignore_error](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L89) option on the servergroup.

**Comment by glightfoot** [comment]
thanks!
