### ISSUE TITLE
no metrics since 0.0.53

### ISSUE THREAD

**Issue by strowi** [jacksontj/promxy#244]
Hi,

we are running promxy in front of victoriametrics. Since v0.0.53 there are no metrics returned from a simple "up" query. Can't see anything special in debug logs:

```
...
DEBU[2019-11-19T14:07:53+01:00] https://$URL/victoria/         api=Query query=up ts="2019-11-19 14:07:53.13 +0100 CET"
DEBU[2019-11-19T14:07:53+01:00] https://$URL/victoria/         api=Query query=up took=221.539703ms ts="2019-11-19 14:07:53.13 +0100 CET"
127.0.0.1 - - [19/Nov/2019 13:07:53] "GET /api/v1/query HTTP/1.1 200 87" 0.224690 query=up&time=1574168873.13&_=1574168871007
```

regards,
strowi

**Comment by sw0x2A** [comment]
I see a similar issue. I am a new user of promxy, started with version 0.0.56. I haven't tested another version. Also promxy in front of VictoriaMetrics.

Queries like up have an empty result when asking for current values. If you ask for time NOW-2m, the expected values are returned. Seems like some aggregation of the last minute fails or so.

**Comment by jacksontj** [comment]
I was able to reproduce this behavior, unfortunately it is not a promxy bug :( This is actually a case of the `nocache` option to VM not being honored for points still in memory (https://github.com/VictoriaMetrics/VictoriaMetrics/issues/241). It seems that the bug was partially mitigated previously because promxy was querying [more data than necessary](https://github.com/jacksontj/promxy/commit/c2454bb3d4081cec103a06c99eedaa67d1d140fe) which seems to mitigate the issue. With the issue upstream I don't plan on putting any workarounds in promxy (as this should be a simple fix upstream).

**Comment by strowi** [comment]
thx for looking into this! I'll monitor the upstream issue.
