### ISSUE TITLE
TLS client cert support?

### ISSUE THREAD

**Issue by deucedaily** [jacksontj/promxy#265]
Hi.  I am trying to setup a proxy to a prometheus instance that uses TLS certs for client authentication.  I was looking through the sample configs and documentation but I only see `insecure_skip_verify` as a configuration option related to TLS.  Is this a supported feature of your project?

**Comment by jacksontj** [comment]
Thanks for reaching out! The `tls_config` section promxy is using is actually the same as from prometheus. So this means all the same options (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config) work -- so you should be able to define all those options (CA, cert, key, servername, etc.).

If you run into problems definitely let me know (as it is expected to work).

**Comment by deucedaily** [comment]
Thanks for the info.  I was able to set the configuration, but I can't get any information to see if it is working.  I'm not sure if your project can support what I'm trying to fix.  I'm trying to setup federation between 2 prometheus.  `One` is packaged by a vendor and requires client certs to authenticate.  `Two` is packaged by an internal team that does not support adding certs to the stack right now.  I was hoping that I could use promxy to connect to `One` with the certs, and then `Two` could connect to promxy and retrieve the data.  As both of the instances I'm trying to connect are "managed" I'm not sure how much flexibility I have.  Can I setup a scrape job to pull from promxy, or is this outside of the scope of promxy?

**Comment by jacksontj** [comment]
So what you are describing (just adding certs to the request) might be better implemented with a simple HTTP proxy (e.g. NGINX / HAProxy).

Promxy is intended as an aggregating proxy -- so it has full insight into the API and the data passing by to aggregate data between many prometheus API endpoints. This is usually done *instead* of federation (since federation requires re-scraping, whereas promxy aggregates at query time). So based on what I'm reading here I think you might want to have promxy connect to both `One` and `Two` and do the aggregation itself -- this way all queries would be routed to promxy which would do the aggregation on-the-fly (instead of having to scrape all the metrics from `One` into `Two`).

**Comment by deucedaily** [comment]
Thanks for the feedback.  I sort of agree and figured that may be what you would say.  I was having issues finding a solution to "inject" the cert through some other http proxy, so I was looking to see if I could make promxy do something similar.  I finally was able to work with our load balancer team and get a working configuration, but I'm still considering using promxy for it's intended purpose on some other instances.
