### ISSUE TITLE
how to pass remote URL to read in promxy config

### ISSUE THREAD

**Issue by veer123prathap** [jacksontj/promxy#294]
Hi, we are confused with promxy

we need to install promxy same namespace or different namespace in the cluster how to pass remote URL to read in promxy config

can anyone help me on this, please

Thanks

**Comment by miklosn** [comment]
I have a similar question. My prometheus instances are available on a different URI prefix (/prometheus). Any way to specify it?

**Comment by jacksontj** [comment]
> we need to install promxy same namespace or different namespace in the cluster

I assume you mean in a k8s namespace? If so thats entirely up to you, it just needs network level access (doesn't have to be in the same namespace).

> how to pass remote URL to read in promxy config

I assume you want to override the path for the downstream prometheus API (similar question as @miklosn ) if so that can be specified with `path_prefix` -- https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L48
