### ISSUE TITLE
How to interprate metrics server_group_request_duration_.* ?

### ISSUE THREAD

**Issue by splawik86** [jacksontj/promxy#320]
Hello!

I've one bothering question. Metrics server_group_request_duration_seconds_sum/count have label "status". I'm very interesting what this status 'error' exactly means?  I checked promxy logs and I've noticed nothing response codes != 200 yet, but the graph show something completely different. 
<img width="831" alt="Zrzut ekranu 2020-06-29 o 13 48 46" src="https://user-images.githubusercontent.com/11768079/86001522-4732aa80-ba0f-11ea-83c1-94e5e7eb3c0c.png">

**Comment by jacksontj** [comment]
This metric (
https://github.com/jacksontj/promxy/blob/master/pkg/servergroup/servergroup.go#L35)
represents the status of the individual servers within the servergroups. So
its actually quite possible to get errors talking to 1 of the downstream
servers within a servergroup and still have promxy return a result (either
because another in the servergroup responded, or because errors are
configured to be ignored).

**Comment by jacksontj** [comment]
I hope that my previous response was sufficient to answer the question. Its been a week with no reply so I'm going to assume it was, if it wasn't please feel free to re-open :)
