### ISSUE TITLE
Please clarify configuration with alerting and remote_write

### ISSUE THREAD

**Issue by vkuznet** [jacksontj/promxy#370]
Hi,
I'm new to the tool and trying to understand how to properly configure it. I searched on the internet and tried freenode chat, but so far no success.

I would like to understand how properly configuring alerting and remote_write. If I have 2 prometheus servers I can run along with them the AlertManager (AM). But in promxy I do have alerting section in configuration as well. How I can aggregate alerts from my prometheus servers? Should I run AM along with promxy, enable alerting section in promxy and disable alerting in prometheus? Or, do I need to still use AM with prometheus and then configure promxy accordingly? I also would like to understand the usage of remove_write and how it will be related to this setup.

I would greatly appreciate if you'll point me to more documentation on these topics.
Thanks,
Valentin.

**Comment by jacksontj** [comment]
@vkuznet thanks for reaching out (and sorry about the not-so-active freenode). Promxy's alert processing is the same as prometheus' -- it just queries across the aggregated data. So you'd still need to have AlertManager for promxy to send its alerts to -- so they can integrate with whatever escalation system you are using.

This is (at least indirectly?) covered in the example config [here](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L15); hopefully that clears up the alerting side of things.

Remote_write is a bit more confusing -- high-level its [just an appender](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L22) so all local metrics generated would be sent there. In practice metrics are generated by (1) recording rules (2) alerting rules. There was a previous question (#324) that covers this in a bit more detail. Unfortunately since prometheus doesn't have a way to really _write_ the data; we're left with sending it somewhere and leaving it up to the user to figure out how to get it into their metrics system (if using prometheus we provide an exporter; some others e.g. VictoriaMetrics support writing; so direct sending is possible).


Hopefully that clears things up a bit; I would definitely appreciate any help with improving the docs -- PRs definitely very welcome :)

**Comment by yogeek** [comment]
Hi @jacksontj , we have Prometheus Operator that deploys:
  - 2 prometheus instances (1 statefulset with 2 pods)
  - 1 alertmanager cluster (1 statefulset with 3 pods)
  - a default prometheus config with a set of rules (records, alerts...)
And then we deploy our own rules using the Prometheus operator CRDs (PrometheusRules...)

With this config, the "state" (metrics, alerts, ...) are stored in prometheus.

Now, we just added promxy in front of our prometheus endpoints : as promxy has no storage, how alerting rules and evaluation are stored ? (I do not see any PV/disk mounted in the promxy deployment)

If, as you explained above, Promxy is responsible for alert processing, I guess we have to remove the default Alert processing config that comes natively with Prometheus operator, right ? (to avoid having it both in prometheus and promxy)
If this is right, do you know how this must be done with Prometheus operator ?

Do we need to add a remote storage like VictoriaMetrics for this ?

**Comment by vkuznet** [comment]
@jacksontj thanks for reply. The remote_write is clear and we do use VictoriaMetrics. But AM part still requires some thinking. While I was awaiting your reply I came across this [blog](https://www.robustperception.io/high-availability-prometheus-alerting-and-notification). In this setup they place AM along with Prometheus but in a cluster mode such that AM instances talk to each other. What you suggest is to place AM along with Promxy and let promxy talk to Prometheus/VM services. The alert rules in this case will reside in promxy, and in fact the promxy setup will be identical to Prometheus in that case, i.e. it will have AM section and rules. I'm not sure which setup is more suitable but I appreciate clarification.

**Comment by jacksontj** [comment]
@yogeek These metrics from promxy (e.g. recording rules and ALERT_STATE metrics) are sent to the configured `remote_write` endpoint. Some examples of usage can be found in https://github.com/jacksontj/promxy/issues/324 -- but TLDR you can either send them direct to something with a remote write endpoint (e.g. VictoriaMetrics) or use the included [remote_write_exporter](https://github.com/jacksontj/promxy/tree/master/cmd/remote_write_exporter) and scrape that from prometheus.

@vkuznet To clarify here; the interaction between promxy and AM is the same as between prometheus and AM (as a matter of fact promxy is using the same code to both execute the rules and talk to AM!). The main advantage of putting rules at the promxy layer is that those alerts can access aggregated metrics (e.g. "total QPS across all prometheus nodes").

**Comment by jacksontj** [comment]
Hopefully my last comment finished answering this, since its been a while with no response I'm assuming its all covered. If there are additional questions/comments/concerns please feel free to re-open.
