### ISSUE TITLE
Querying /api/v1/rules?type=alert returns an empty response

### ISSUE THREAD

**Issue by robertjsullivan** [jacksontj/promxy#406]
We're fronting a couple Prometheis with Promxy and we're seeing the Prometheus UI have an empty Alerts tab when accessed via Promxy. I believe the issue is coming down to this query against promxy:

```
curl http://localhost:8082/api/v1/rules?type=alert
{"status":"success","data":{"groups":[]}}
```

When running that directly against Prometheus we get lots of alerts returned.

Is this intentional?  Or would it be something that's easy to fix? I'm happy to work on a PR given some direction.

**Comment by jacksontj** [comment]
This is actually somewhat intended; albeit confusing. This API endpoint returns the list of rules for the given type that the endpoint is processing. Promxy itself actually processes its own rules (recording and alerting). So unlike the query APIs that combine downstream data -- this one is actually returning local data (the rules that it is configured to process). This is intentional because "combining alerts" is something left up to alertmanager :)
