### ISSUE TITLE
Incorrect duration modifications

### ISSUE THREAD

**Issue by shweppsie** [jacksontj/promxy#436]
I'm seeing an issue where durations like 25h are being converted to 1d1h which victoriametrics cannot parse. I expect them to be passed unmodified from the original query.

Query: max_over_time(solar_charge_state[25h])
Error: Error executing query: 422: error when executing query="max_over_time(solar_charge_state[1d1h])" for (time=1623730732832, step=300000): windowAndStep: unexpected token "1h"; want "]"; unparsed data: "1h])"

Query: max_over_time(solar_charge_state[121m])
Error: Error executing query: 422: error when executing query="max_over_time(solar_charge_state[2h1m])" for (time=1623730755150, step=300000): windowAndStep: unexpected token "1m"; want "]"; unparsed data: "1m])"

```
/ $ promxy --version
Version v0.0.70
```

**Comment by jacksontj** [comment]
That is unfortunate that victoriametrics doesn't support the time ranges properly :/ Since promxy parses and creates its own queries it is actually expected that they may not match; but it is surprising that VM doesn't properly support the various time ranges that prometheus does. From your examples here it seems that VM doesn't support mixed times in the duration (which is valid time.Duration); I'd suggest creating a feature request in VM to add support for these duration formats.

We could potentially change promxy to always pick "the smallest" single unit; but I'm not sure I want to get into being so particular because a specific downstream doesn't support the API properly.

**Comment by shweppsie** [comment]
Thanks for the prompt reply @jacksontj.

Ah, I didn't realise these mixed times were valid promql (though I am aware they look exactly like golang durations). I'm happy to raise it over at victoriametrics instead. I'll wait for them to confirm it's something they're going to fix before closing this off if that's okay?

**Comment by jacksontj** [comment]
That works for me. Please reference the this issue in the VM one so it
links (as I'm sure you won't be the only one to hit this problem :) )

**Comment by valyala** [comment]
VictoriaMetrics supports composite time ranges such as `1d1h` starting from v1.41.1 . See the corresponding commit - https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0e533d1a9c8e37f286d318ac9dad5c3ba493a48c . I'd recommend upgrading VictoriaMetrics to the [latest available release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [upgrade instructions](https://docs.victoriametrics.com/#how-to-upgrade-victoriametrics).

**Comment by shweppsie** [comment]
Ah, thanks! I was planning to upgrade our instance before creating an issue against VM but you beat me to it. Thanks @valyala !

**Comment by shweppsie** [comment]
This has resolved the issue, thanks team!
