### ISSUE TITLE
The compiled ARM64 version requests an error

### ISSUE THREAD

**Issue by caizhiyong88** [jacksontj/promxy#437]
Error opening React index.html: open static/react/index.html: no such file or directory

**Comment by jacksontj** [comment]
Thanks for reporting! I did some quick looking and it seems that the upstream prometheus mechanism for packing the static content doesn't handle cross-arch builds well. So this will require some changes to promxy's build scripting. I think I have some pi around somewhere to test on this; but full-disclosure this is pretty low on my priority list (although it should be a pretty straight-forward first-PR if someone wanted to tackle this).

**Comment by tvi** [comment]
I think c2c8a00ec47b759dd32d9f983d5464e35733abfb fixed this issue.

**Comment by jacksontj** [comment]
I was able to successfully run the latest master on my old raspberry pi 2 B+ (32 bit arm); the static content builds (the cause of the issues previously) had to be reworked as part of #544 so the issue seems resolved.

As such I'm actually going to add release builds for those platforms as well -- https://github.com/jacksontj/promxy/pull/556
