### ISSUE TITLE
prometheus rules are delayed to take effect

### ISSUE THREAD

**Issue by zgqqiang** [jacksontj/promxy#481]
When a large number of prometheus rules are added at the same time, one prometheus rule is reloaded. As a result, the prometheus rule has been created but does not take effect. When 1000 prometheus rules are created at the same time, the alarm configuration takes effect 2 minutes later.

**Comment by jacksontj** [comment]
@zgqqiang promxy is just using the same rules libs as prometheus; so I'd expect you'd get comparable performance with those same rules on prometheus directly. Would you be able to test loading those same rules on prometheus to compare the load times?

**Comment by zgqqiang** [comment]
We use prometheus-operator. We find that prometheus-operator does not have this problem. They do not reload a new prometheus rule, which wastes performance. The prometheus-operator aggregates all prometheus rules into multiple configmaps at a time, updates the configmap, podmonitor, and servicemonitor to secret, and checks whether the secret is the same as the last one. If not, reloads the configmap. In this way, reload will not be frequently invoked. In addition, if a large number of prometheus rules are created at a time, prometheus will be frequently invoked during the reload process by the Promxy. As a result, the CPU usage of prometheus increases sharply. If health check is configured for the Prometheus and the CPU usage is small, the Prometheus health check times out and restarts.

**Comment by jacksontj** [comment]
So if I'm understanding correctly the CRD in the operator maps to a single configmap; so if there is a change to 1 CRD it reloads a single rule instead of many. If this is the case you should get comparable performance by splitting the rules in promxy into many smaller files (as its using the same library).

Promxy: https://github.com/jacksontj/promxy/blob/master/cmd/promxy/main.go#L323
prometheus: https://github.com/prometheus/prometheus/blob/main/cmd/prometheus/main.go#L713

**Comment by zgqqiang** [comment]
Thank you
