### ISSUE TITLE
Cannot install promxy

### ISSUE THREAD

**Issue by Wing924** [jacksontj/promxy#5]
```
[root@promxy-poc ~]# go get -u github.com/jacksontj/promxy/cmd/promxy
package github.com/prometheus/prometheus/storage/metric: cannot find package "github.com/prometheus/prometheus/storage/metric" in any of:
	/usr/local/go/src/github.com/prometheus/prometheus/storage/metric (from $GOROOT)
	/root/go/src/github.com/prometheus/prometheus/storage/metric (from $GOPATH)
package github.com/prometheus/prometheus/storage/local: cannot find package "github.com/prometheus/prometheus/storage/local" in any of:
	/usr/local/go/src/github.com/prometheus/prometheus/storage/local (from $GOROOT)
	/root/go/src/github.com/prometheus/prometheus/storage/local (from $GOPATH)
```

**Comment by tvi** [comment]
Let me look at it

**Comment by jacksontj** [comment]
My expectation is that this is due to a change in prometheus deps. `go get` doesn't honor the dependencies pinned using `dep`. I don't believe there is a way around that-- if not then I'll update the docs to suggest a `go get github.com/jacksontj/promxy`, `dep ensure`, then `cd cmd/promxy && go build` -- or wrap that all up in a Makefile

**Comment by jacksontj** [comment]
github decided to auto-close this with no comment :). I merged in the vendor directory just now, so that should resolve this issue.
