### ISSUE TITLE
[nip] in pkg/remote/storage.go line 376. we may use RLock instead? 

### ISSUE THREAD

**Issue by KEIONG** [jacksontj/promxy#566]
sry for my noobness and poor englinsh. I read source code of promxy these days. for this nip: we just read the value of queryables, why not use rlock instead

**Comment by KEIONG** [comment]
I see the similar code in prometheus.  I think i am wrong now, but dont know why.

**Comment by jacksontj** [comment]
So this `remote` package is actually just an older version from upstream prometheus. Unfortunately I had to fork their client as they made changes to the API which made their version not general purpose.

From my quick look at https://github.com/prometheus/prometheus/blob/main/storage/remote/storage.go#L149-L151 (what I assume you are referring to) I'm not sure why they aren't using an RLock (since it is a read not a write) but I imagine the perf impact isn't massive here in general

**Comment by KEIONG** [comment]
> So this `remote` package is actually just an older version from upstream prometheus. Unfortunately I had to fork their client as they made changes to the API which made their version not general purpose.
> 
> From my quick look at https://github.com/prometheus/prometheus/blob/main/storage/remote/storage.go#L149-L151 (what I assume you are referring to) I'm not sure why they aren't using an RLock (since it is a read not a write) but I imagine the perf impact isn't massive here in general

its really helpful. thank you very much
