### ISSUE TITLE
Add Docker image

### ISSUE THREAD

**Issue by palmerabollo** [jacksontj/promxy#58]
It would be great to have a Dockerfile and a ready-to-use docker image.
Are you open to contributions?

**Comment by palmerabollo** [comment]
This works, using alpine as the base image:

```
FROM golang:1.10.3-alpine3.7 as build
RUN apk --no-cache add git
RUN go get -u github.com/jacksontj/promxy/cmd/promxy

FROM alpine:3.7
COPY --from=build /go/bin/promxy /bin/promxy
ENTRYPOINT [ "promxy" ]
CMD [ "--help" ]
```

**Comment by jacksontj** [comment]
One thing to keep in mind with the docker containers, as it stands today promxy requires a config file -- so this will require you to layer that in. If you are using kubernetes this is quite simple, but figured I'd call that out anyways :)

I created a PR (#64) with a dockerfile, I chose to use "scratch" to make the image even smaller (since its a single go binary anyways).
