### ISSUE TITLE
Does Promxy support query pushdown？

### ISSUE THREAD

**Issue by darcydai** [jacksontj/promxy#584]
in our case, we use the VM cluster to support region-level metrics store and query.  we want to use Promxy to support global aggregation queries.  Does Promxy pull all time-series data from upstream  (VM) in memory and then evaluate the query? 
![image](https://user-images.githubusercontent.com/20854418/228576002-524925d6-7388-4237-bb1c-c7a57c0ed514.png)

**Comment by darcydai** [comment]
Haha, I found some context about this https://github.com/thanos-io/thanos/issues/305

**Comment by jacksontj** [comment]
Thanks for reaching out! The short answer is yes -- promxy does a lot of "query pushdown" work (as detailed in that thanos issue of mine). The main key here being that promxy (where at all possible) will push queries as close to the data as possible.

So for example, if we wanted `sum(foo)` instead of pulling raw data from all regional endpoints into promxy and then summing -- we instead send `sum(foo)` to each region then sum the sums. There is obviously a lot more context/detail on how this works in practice -- but this is the main "secret sauce" to promxy that gives it so much better performance than other naive solutions.

**Comment by darcydai** [comment]
thanks a lot,  great job you are doing!
