### ISSUE TITLE
/api/v1/series and /api/v1/labels use http GET method to downstream server may cause http 414 error

### ISSUE THREAD

**Issue by pyfdtic** [jacksontj/promxy#588]
we meet http 414 error in our enviroment, url is `/api/v1/series`,
our request link like `grafana -> promxy -> vm`, after dig a while we found promxy use http GET method to request downstream prometheus server, code in  https://github.com/jacksontj/promxy/blob/master/vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go#L1036  and https://github.com/jacksontj/promxy/blob/master/vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go#L1163 .

is there a design for this ?  or it's a bug ?

**Comment by jacksontj** [comment]
This looks like a "missing feature" in the `client_golang`. I added the GET with POST fallback for query and query _range previously (https://github.com/jacksontj/client_golang/commit/7d0e24eeac0ff1e5b71721beb22881169b83bb80) but looking at the API docs it seems that some other APIs support POST as well -- so that would require similar updates to those methods.

**Comment by jacksontj** [comment]
PR created upstream: https://github.com/prometheus/client_golang/pull/1252
