### ISSUE TITLE
The count function does not execute correctly

### ISSUE THREAD

**Issue by resurgence72** [jacksontj/promxy#632]
hi，At present, our tsdb is only used as a storage role, and I used three tsdb as data shard storage, that is, each tsdb only stores 1/3 of the data. And promxy is used as the query side.
Currently I have a simple promql 'prober_agent_is_alive==1' that executes alone and hits 17 series；
![image](https://github.com/jacksontj/promxy/assets/70791908/ea6d45f9-1ca0-46bd-abf2-71d5127c4041)
Then I want to use the `count` function to calculate the total number of the series, but the final result is 8, in my understanding, count should be the same as the total number of the series. 
![image](https://github.com/jacksontj/promxy/assets/70791908/2dabbc07-c3ff-49a8-a572-a12ab41a682a)

But when I used the prometheus remote read structure, the statement returned the correct result.
![image](https://github.com/jacksontj/promxy/assets/70791908/71ae1d4e-51ac-4c05-aba6-cfd5ae41df0f)

**Comment by resurgence72** [comment]
hi,this is my config
`
    global:
    promxy:
      server_groups:
      - static_configs:
          - targets:
            - prometheus-shard-0.prometheus-shard.monitor:9090
            - prometheus-shard-1.prometheus-shard.monitor:9090
            - prometheus-shard-2.prometheus-shard.monitor:9090
        anti_affinity: 1m
        timeout: 30s
`

**Comment by resurgence72** [comment]
After I removed the 'anti_affinity' configuration, the query returned to normal. It seems that it is caused by anti_affinity. I need to study the function of this parameter again.

**Comment by jacksontj** [comment]
@resurgence72 from a quick glance at this issue; I believe the issue is with your servergroup configuration. What you described above is that each of these 3 shards hold unique data; if so then they should each have their own servergroup config with labels (discussion about this in https://github.com/jacksontj/promxy/issues/260).

Otherwise promxy believes the 3 have the same data and will only "fill" if there are holes -- which there probably aren't unless there is no anti_affinity config (which forces it to merge always).

Hopefully that'll help!
