### ISSUE TITLE
Add support for `--web.route-prefix`

### ISSUE THREAD

**Issue by sushovan23** [jacksontj/promxy#636]
I have deployed promxy in k8s using helm chart. exposing it using nginx ingress controller however I want to access it using endpoint like /promxy-prod instead of just /
If there any configuration available to set httpprefix path?

**Comment by sushovan23** [comment]
may be something similar to what prometheus provides with --web.route-prefix

**Comment by jacksontj** [comment]
Thanks for the question! As of today the only mechanism supported as of now is to use the [`externalUrl`](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/main.go#L92) -- but it seems that upstream has since added a `--web.route-prefix` as well, so we could add that to promxy to match.

But if you need something *now* using externalUrl will do the trick (thats what I've been using).
