### ISSUE TITLE
Unable to integrate sso enabled promxy with grafana 10 

### ISSUE THREAD

**Issue by bhagavancp** [jacksontj/promxy#655]
we have integrated promxy with SSO and when trying to connect through  grafana 10 it is failing with below error : 

logger=tsdb.prometheus t=2024-05-23T18:23:58.985347539Z level=warn msg="Failed to get prometheus buildinfo" err="error querying resource: Get \"https://sso.com/ssoi/auth?method=GET&requestid=7782233d-39ce-42a5-8679-04bcf866a7c1&target=https%3A%2F%2Fpromxy-dev.com%2Fapi%2Fv1%2Fstatus%2Fbuildinfo\": EOF"
logger=tsdb.prometheus endpoint=checkHealth pluginId=prometheus dsName="FF Prometheus" dsUID=c1837ab5-5c14-4f60-8b27-12351ae491ac uname="ABC" t=2024-05-23T18:23:58.985386185Z level=warn msg="Failed to get prometheus heuristics" err="failed to get buildinfo: error querying resource: Get \"https://sso.com/ssoi/auth?method=GET&requestid=7782233d-39ce-42a5-8679-04bcf866a7c1&target=https%3A%2F%2Fpromxy-dev.com%2Fapi%2Fv1%2Fstatus%2Fbuildinfo\": EOF"
logger=context userId=2 orgId=1 uname="ABC" t=2024-05-23T18:23:58.985459836Z level=info msg="Request Completed" method=GET path=/api/datasources/uid/c1837ab5-5c14-4f60-8b27-12351ae491ac/health status=400 remote_addr=10.x.x.x time_ms=53 duration=53.418222ms size=301 referer=https://grafana.com/connections/datasources/edit/c1837ab5-5c14-4f60-8b27-12351ae491ac handler=/api/datasources/uid/:uid/health

**Comment by jacksontj** [comment]
First off; thanks for reaching out! Always happy to see more users of the project :) Alright; lets dive in!


> we have integrated promxy with SSO

I'm not quite sure what this means. I assume this means you have some SSO proxy in front of promxy?

> when trying to connect through grafana 10 it is failing with below error

I assume this means when grafana is trying to connect to promxy (which itself is behind som eSSO proxy)

> msg="Failed to get prometheus heuristics" err="failed to get buildinfo: error querying resource: Get "https://sso.com/ssoi/auth?method=GET&requestid=7782233d-39ce-42a5-8679-04bcf866a7c1&target=https%3A%2F%2Fpromxy-dev.com%2Fapi%2Fv1%2Fstatus%2Fbuildinfo\": EOF"

First off; these look like logs from grafana (correct me if I'm wrong :D ). The URL here is an SSO auth URL which is not "normal" (as this should be a prom API query). So I'm guessing what is happening here is grafana is making a call to promxy and getting a redirect to an SSO URL -- which is failing. So there are two issues here that I see:

1) grafana's call to promxy is going through some SSO redirect flow -- this seems unexpected as grafana isn't a person -- so I'd expect some sort of service account or something.

2) grafana is uanble to talk to the SSO endpoint (gets an EOF). The EOF makes me think its some sort of firewall or proxy issue -- otherwise I'd expect a not authorized error of some type.

**Comment by jacksontj** [comment]
Its been ~6 week with no response; so I'm going to hope/assume that the issue was resolved. If not please feel free to re-open and we can pick up where this left off!
