### ISSUE TITLE
Promxy crashes due to out of memory on some request

### ISSUE THREAD

**Issue by Maksprots** [jacksontj/promxy#669]
Hi! We have some problems with failing promxy on one type of request.  

In our project we use prom-label-proxy and it adds label filters to http params and post body.  
POST: /api/v1/series?match[]={some_label="some_name"}  
Body:
end=1722367950&match[]={__name__="some_metric",some_label="some_name"}&start=1722346350. 

The request above breaks promxy and and he falls due to out of memory.
But if we leave  params or body then everything is ok.  
Prom-label-proxy is added to both places citing the fact that they do not know that Prometheus has a priority for body or params: https://github.com/prometheus-community/prom-label-proxy/commit/f660bc3d1d0df4bcf79ac81fbfec3292c239d6bf . 

Please tell me is this a bug or a feature?

**Comment by jacksontj** [comment]
Unfortunately I'm a bit lost on the scenario here. From what is pasted here it looks like the URL and the body have different selectors -- which is fine. Promxy is actually using the prometheus webhandler for this which seems to [support either](https://github.com/prometheus/prometheus/blob/main/web/api/v1/api.go#L830-L835) -- with [body taking priority](https://pkg.go.dev/net/http#Request.ParseForm).

> Prom-label-proxy is added to both places citing the fact that they do not know that Prometheus has a priority for body or  params:

That is a bit curious. Prometheus definitely prefers the body -- but supports both. I think the reason that they may keep that around is that we don't know if the API *supports* POST (same issue happened in the [client_golang](https://github.com/prometheus/client_golang/issues/428)).

The real issue here seems to be an OOM -- which is likely just some query selecting too many series and pulling everything into memory. So my expectation is that the filter is insufficient and pulling too much data. Would you be able to provide the query, debug/trace logs, and/or a tcpdump?

**Comment by jacksontj** [comment]
As its been ~2 months with no reply I'm going to go ahead and close this issue. But if this is still an issue and you want to resume discussion feel free to re-open or create another issue!
