### ISSUE TITLE
Add user authentication/ basic auth for promxy http server

### ISSUE THREAD

**Issue by jenningsloy318** [jacksontj/promxy#97]
As  we can treat promxy   as reverse  proxy server for backend prometheus instance, so want promxy add support user authentication, which is lack in prometheus.

**Comment by jacksontj** [comment]
Definitely sounds like a reasonable thing to add. I could imagine people wanting a variety of auth mechanism (oauth, basic auth, etc.). Ideally there'd be some middleware or something that could provide that. I did some quick googling and https://github.com/qor/auth looks like a possibility.

I have a couple questions about this request:
1. are you wanting *just* basic auth? Or are there other auth mechanisms to cover as well.
2. how do you want auth to work? are you expecting per-path authorization? or just allowed/disallowed?



As it stands right now you can achieve this by adding in nginx (or some other proxy with basic auth), but I do agree it would be nice to include as part of the daemon.

**Comment by vsliouniaev** [comment]
This sounds like it would be just adding a feature that is already provided by standalone proxy authentication mechanisms that exist

**Comment by jacksontj** [comment]
@vsliouniaev true, I think auth inside promxy could be interesting if we wanted to have more sophisticated metrics permissions, but the more I think on it -- the more complex/undefined that is (especially since prom itself has no permissions around metrics). So, I think I'll instead take this as the opportunity to publish default k8s manifests with some example configurations (by itself, with nginx auth, etc.).
